# fly.toml app configuration file generated for pets-secret-garden-laravel-modify on 2024-10-02T11:57:46+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pets-secret-garden-laravel-modify'
primary_region = 'nrt'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '7.4'

[deploy]
  release_command = "php /var/www/html/artisan migrate --force"

[env]
  APP_ENV = 'production'
  LOG_CHANNEL = 'daily'
  LOG_LEVEL = 'info'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'
  DB_CONNECTION = "mysql"
  DB_HOST = "demo-mysql-2.internal"
  DB_DATABASE= "pets_secret_garden"
  DB_USERNAME="non_root_user"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
